/**
 * Initial Canonical Template
 *
 * A modern, responsive SaaS / Agency landing page with stable element IDs,
 * comprehensive typography, appearance, and responsive overrides.
 */

import { ElementModel, TemplateModel } from './types';

const elements: Record<string, ElementModel> = {
  // === HEADER SECTION ===
  header: {
    id: 'header',
    name: 'Header Section',
    type: 'section',
    children: ['header-container'],
    base: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#f1f5f9',
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 24,
      paddingRight: 24,
      display: 'block',
      width: '100%',
    },
    overrides: {
      mobile: {
        paddingLeft: 16,
        paddingRight: 16,
        paddingTop: 12,
        paddingBottom: 12,
      },
    },
    revision: 1,
  },
  'header-container': {
    id: 'header-container',
    name: 'Header Container',
    type: 'container',
    parentId: 'header',
    children: ['logo', 'nav-container', 'header-cta'],
    base: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'between',
      maxWidth: '1200px',
      width: '100%',
    },
    overrides: {},
    revision: 1,
  },
  logo: {
    id: 'logo',
    name: 'Brand Logo',
    type: 'heading',
    parentId: 'header-container',
    base: {
      text: '✦ AURA STUDIO',
      fontSize: 18,
      fontWeight: 'bold',
      color: '#0f172a',
      letterSpacing: '0.04em',
    },
    overrides: {
      mobile: {
        fontSize: 16,
      },
    },
    revision: 1,
  },
  'nav-container': {
    id: 'nav-container',
    name: 'Navigation Bar',
    type: 'container',
    parentId: 'header-container',
    children: ['nav-features', 'nav-platform', 'nav-pricing', 'nav-about'],
    base: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 28,
    },
    overrides: {
      tablet: {
        gap: 16,
      },
      mobile: {
        display: 'none', // Hidden on mobile for clean mobile navigation
      },
    },
    revision: 1,
  },
  'nav-features': {
    id: 'nav-features',
    name: 'Nav: Features',
    type: 'nav-item',
    parentId: 'nav-container',
    base: {
      text: 'Features',
      fontSize: 14,
      fontWeight: 'medium',
      color: '#475569',
    },
    overrides: {},
    revision: 1,
  },
  'nav-platform': {
    id: 'nav-platform',
    name: 'Nav: Platform',
    type: 'nav-item',
    parentId: 'nav-container',
    base: {
      text: 'Platform',
      fontSize: 14,
      fontWeight: 'medium',
      color: '#475569',
    },
    overrides: {},
    revision: 1,
  },
  'nav-pricing': {
    id: 'nav-pricing',
    name: 'Nav: Pricing',
    type: 'nav-item',
    parentId: 'nav-container',
    base: {
      text: 'Pricing',
      fontSize: 14,
      fontWeight: 'medium',
      color: '#475569',
    },
    overrides: {},
    revision: 1,
  },
  'nav-about': {
    id: 'nav-about',
    name: 'Nav: About',
    type: 'nav-item',
    parentId: 'nav-container',
    base: {
      text: 'Company',
      fontSize: 14,
      fontWeight: 'medium',
      color: '#475569',
    },
    overrides: {},
    revision: 1,
  },
  'header-cta': {
    id: 'header-cta',
    name: 'Header CTA Button',
    type: 'button',
    parentId: 'header-container',
    base: {
      text: 'Book Demo',
      fontSize: 13,
      fontWeight: 'semibold',
      color: '#ffffff',
      backgroundColor: '#0f172a',
      borderRadius: 8,
      paddingTop: 8,
      paddingBottom: 8,
      paddingLeft: 16,
      paddingRight: 16,
    },
    overrides: {
      mobile: {
        fontSize: 12,
        paddingLeft: 12,
        paddingRight: 12,
      },
    },
    revision: 1,
  },

  // === HERO SECTION ===
  hero: {
    id: 'hero',
    name: 'Hero Section',
    type: 'section',
    children: ['hero-container'],
    base: {
      backgroundColor: '#fafafa',
      paddingTop: 72,
      paddingBottom: 80,
      paddingLeft: 24,
      paddingRight: 24,
      borderWidth: 1,
      borderColor: '#f1f5f9',
      width: '100%',
    },
    overrides: {
      tablet: {
        paddingTop: 56,
        paddingBottom: 64,
      },
      mobile: {
        paddingTop: 40,
        paddingBottom: 48,
        paddingLeft: 16,
        paddingRight: 16,
      },
    },
    revision: 1,
  },
  'hero-container': {
    id: 'hero-container',
    name: 'Hero Container',
    type: 'container',
    parentId: 'hero',
    children: ['hero-eyebrow', 'hero-title', 'hero-description', 'hero-cta-group', 'hero-metric-card'],
    base: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      maxWidth: '860px',
      width: '100%',
    },
    overrides: {},
    revision: 1,
  },
  'hero-eyebrow': {
    id: 'hero-eyebrow',
    name: 'Hero Eyebrow Badge',
    type: 'badge',
    parentId: 'hero-container',
    base: {
      text: '✦ DETERMINISTIC SCOPED AI PLATFORM 2.0',
      fontSize: 12,
      fontWeight: 'bold',
      color: '#4338ca',
      backgroundColor: '#eef2ff',
      borderColor: '#c7d2fe',
      borderWidth: 1,
      borderRadius: 999,
      paddingTop: 6,
      paddingBottom: 6,
      paddingLeft: 16,
      paddingRight: 16,
      marginBottom: 20,
      letterSpacing: '0.05em',
    },
    overrides: {
      mobile: {
        fontSize: 10,
        paddingLeft: 12,
        paddingRight: 12,
        marginBottom: 14,
      },
    },
    revision: 1,
  },
  'hero-title': {
    id: 'hero-title',
    name: 'Hero Title',
    type: 'heading',
    parentId: 'hero-container',
    base: {
      text: 'Build Safe Web Experiences with Scoped AI Precision',
      fontSize: 48,
      fontWeight: 'extrabold',
      color: '#090d16',
      lineHeight: 1.15,
      textAlign: 'center',
      marginBottom: 20,
      letterSpacing: '-0.03em',
    },
    overrides: {
      tablet: {
        fontSize: 38,
        lineHeight: 1.2,
      },
      mobile: {
        fontSize: 28,
        lineHeight: 1.25,
        marginBottom: 16,
      },
    },
    revision: 1,
  },
  'hero-description': {
    id: 'hero-description',
    name: 'Hero Description',
    type: 'text',
    parentId: 'hero-container',
    base: {
      text: 'Empower non-technical business owners to edit visually or in code, test deterministic AI proposals, and restore single elements with zero risk.',
      fontSize: 18,
      fontWeight: 'normal',
      color: '#475569',
      lineHeight: 1.6,
      textAlign: 'center',
      maxWidth: '680px',
      marginBottom: 32,
    },
    overrides: {
      tablet: {
        fontSize: 16,
        marginBottom: 24,
      },
      mobile: {
        fontSize: 15,
        lineHeight: 1.5,
        marginBottom: 20,
      },
    },
    revision: 1,
  },
  'hero-cta-group': {
    id: 'hero-cta-group',
    name: 'Hero Button Group',
    type: 'container',
    parentId: 'hero-container',
    children: ['hero-primary-cta', 'hero-secondary-cta'],
    base: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
      marginBottom: 40,
    },
    overrides: {
      mobile: {
        flexDirection: 'column',
        width: '100%',
        gap: 12,
        marginBottom: 28,
      },
    },
    revision: 1,
  },
  'hero-primary-cta': {
    id: 'hero-primary-cta',
    name: 'Hero Primary Button',
    type: 'button',
    parentId: 'hero-cta-group',
    base: {
      text: 'Start 14-Day Free Trial →',
      fontSize: 15,
      fontWeight: 'bold',
      color: '#ffffff',
      backgroundColor: '#0f172a',
      borderRadius: 10,
      paddingTop: 12,
      paddingBottom: 12,
      paddingLeft: 24,
      paddingRight: 24,
      shadow: 'md',
    },
    overrides: {
      mobile: {
        width: '100%',
        textAlign: 'center',
        paddingTop: 12,
        paddingBottom: 12,
      },
    },
    revision: 1,
  },
  'hero-secondary-cta': {
    id: 'hero-secondary-cta',
    name: 'Hero Secondary Button',
    type: 'button',
    parentId: 'hero-cta-group',
    base: {
      text: 'Explore Live Showcase',
      fontSize: 15,
      fontWeight: 'semibold',
      color: '#334155',
      backgroundColor: '#ffffff',
      borderColor: '#cbd5e1',
      borderWidth: 1,
      borderRadius: 10,
      paddingTop: 12,
      paddingBottom: 12,
      paddingLeft: 22,
      paddingRight: 22,
    },
    overrides: {
      mobile: {
        width: '100%',
        textAlign: 'center',
      },
    },
    revision: 1,
  },
  'hero-metric-card': {
    id: 'hero-metric-card',
    name: 'Hero Assurance Card',
    type: 'card',
    parentId: 'hero-container',
    children: ['hero-metric-title', 'hero-metric-desc'],
    base: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: 14,
      paddingTop: 16,
      paddingBottom: 16,
      paddingLeft: 24,
      paddingRight: 24,
      shadow: 'sm',
      maxWidth: '560px',
      width: '100%',
    },
    overrides: {
      mobile: {
        paddingLeft: 16,
        paddingRight: 16,
        paddingTop: 14,
        paddingBottom: 14,
      },
    },
    revision: 1,
  },
  'hero-metric-title': {
    id: 'hero-metric-title',
    name: 'Assurance Badge Title',
    type: 'heading',
    parentId: 'hero-metric-card',
    base: {
      text: '✓ 100% Deterministic Scope Isolation',
      fontSize: 14,
      fontWeight: 'bold',
      color: '#0f172a',
      marginBottom: 4,
    },
    overrides: {},
    revision: 1,
  },
  'hero-metric-desc': {
    id: 'hero-metric-desc',
    name: 'Assurance Badge Desc',
    type: 'text',
    parentId: 'hero-metric-card',
    base: {
      text: 'AI proposals and viewport edits can never accidentally mutate unselected elements.',
      fontSize: 13,
      fontWeight: 'normal',
      color: '#64748b',
      lineHeight: 1.4,
    },
    overrides: {},
    revision: 1,
  },

  // === FEATURES SECTION ===
  features: {
    id: 'features',
    name: 'Features Section',
    type: 'section',
    children: ['features-container'],
    base: {
      backgroundColor: '#ffffff',
      paddingTop: 80,
      paddingBottom: 88,
      paddingLeft: 24,
      paddingRight: 24,
      width: '100%',
    },
    overrides: {
      tablet: {
        paddingTop: 64,
        paddingBottom: 72,
      },
      mobile: {
        paddingTop: 48,
        paddingBottom: 56,
        paddingLeft: 16,
        paddingRight: 16,
      },
    },
    revision: 1,
  },
  'features-container': {
    id: 'features-container',
    name: 'Features Container',
    type: 'container',
    parentId: 'features',
    children: ['features-header', 'features-grid'],
    base: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      maxWidth: '1200px',
      width: '100%',
    },
    overrides: {},
    revision: 1,
  },
  'features-header': {
    id: 'features-header',
    name: 'Features Header',
    type: 'container',
    parentId: 'features-container',
    children: ['features-title', 'features-subtitle'],
    base: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      maxWidth: '720px',
      marginBottom: 52,
    },
    overrides: {
      mobile: {
        marginBottom: 32,
      },
    },
    revision: 1,
  },
  'features-title': {
    id: 'features-title',
    name: 'Features Section Title',
    type: 'heading',
    parentId: 'features-header',
    base: {
      text: 'Engineered for Complete Safety & Speed',
      fontSize: 32,
      fontWeight: 'bold',
      color: '#0f172a',
      lineHeight: 1.25,
      marginBottom: 12,
      letterSpacing: '-0.02em',
    },
    overrides: {
      mobile: {
        fontSize: 24,
      },
    },
    revision: 1,
  },
  'features-subtitle': {
    id: 'features-subtitle',
    name: 'Features Section Subtitle',
    type: 'text',
    parentId: 'features-header',
    base: {
      text: 'Every visual tweak, code adjustment, and AI proposal follows the exact same typed validation and commit pipeline.',
      fontSize: 16,
      fontWeight: 'normal',
      color: '#64748b',
      lineHeight: 1.5,
    },
    overrides: {
      mobile: {
        fontSize: 14,
      },
    },
    revision: 1,
  },
  'features-grid': {
    id: 'features-grid',
    name: 'Features 3-Column Grid',
    type: 'grid',
    parentId: 'features-container',
    children: ['feature-1', 'feature-2', 'feature-3'],
    base: {
      display: 'grid',
      gridColumns: 3,
      gap: 24,
      width: '100%',
    },
    overrides: {
      tablet: {
        gridColumns: 2,
        gap: 20,
      },
      mobile: {
        gridColumns: 1,
        gap: 16,
      },
    },
    revision: 1,
  },
  'feature-1': {
    id: 'feature-1',
    name: 'Feature Card 1',
    type: 'card',
    parentId: 'features-grid',
    children: ['feature-1-badge', 'feature-1-title', 'feature-1-desc'],
    base: {
      backgroundColor: '#f8fafc',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: 14,
      paddingTop: 28,
      paddingBottom: 28,
      paddingLeft: 24,
      paddingRight: 24,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      textAlign: 'left',
    },
    overrides: {
      mobile: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 18,
        paddingRight: 18,
      },
    },
    revision: 1,
  },
  'feature-1-badge': {
    id: 'feature-1-badge',
    name: 'Feature 1 Badge',
    type: 'badge',
    parentId: 'feature-1',
    base: {
      text: 'CANONICAL STATE',
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0369a1',
      backgroundColor: '#e0f2fe',
      borderRadius: 6,
      paddingTop: 4,
      paddingBottom: 4,
      paddingLeft: 10,
      paddingRight: 10,
      marginBottom: 16,
      letterSpacing: '0.04em',
    },
    overrides: {},
    revision: 1,
  },
  'feature-1-title': {
    id: 'feature-1-title',
    name: 'Feature 1 Title',
    type: 'heading',
    parentId: 'feature-1',
    base: {
      text: 'Single Source of Truth',
      fontSize: 19,
      fontWeight: 'bold',
      color: '#0f172a',
      marginBottom: 8,
    },
    overrides: {},
    revision: 1,
  },
  'feature-1-desc': {
    id: 'feature-1-desc',
    name: 'Feature 1 Description',
    type: 'text',
    parentId: 'feature-1',
    base: {
      text: 'Typed JSON-serializable template model synchronizes the visual canvas, code editor, and AI demo in real time.',
      fontSize: 14,
      fontWeight: 'normal',
      color: '#475569',
      lineHeight: 1.6,
    },
    overrides: {},
    revision: 1,
  },
  'feature-2': {
    id: 'feature-2',
    name: 'Feature Card 2',
    type: 'card',
    parentId: 'features-grid',
    children: ['feature-2-badge', 'feature-2-title', 'feature-2-desc'],
    base: {
      backgroundColor: '#f8fafc',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: 14,
      paddingTop: 28,
      paddingBottom: 28,
      paddingLeft: 24,
      paddingRight: 24,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      textAlign: 'left',
    },
    overrides: {
      mobile: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 18,
        paddingRight: 18,
      },
    },
    revision: 1,
  },
  'feature-2-badge': {
    id: 'feature-2-badge',
    name: 'Feature 2 Badge',
    type: 'badge',
    parentId: 'feature-2',
    base: {
      text: 'RESPONSIVE SCOPE',
      fontSize: 11,
      fontWeight: 'bold',
      color: '#4338ca',
      backgroundColor: '#eef2ff',
      borderRadius: 6,
      paddingTop: 4,
      paddingBottom: 4,
      paddingLeft: 10,
      paddingRight: 10,
      marginBottom: 16,
      letterSpacing: '0.04em',
    },
    overrides: {},
    revision: 1,
  },
  'feature-2-title': {
    id: 'feature-2-title',
    name: 'Feature 2 Title',
    type: 'heading',
    parentId: 'feature-2',
    base: {
      text: 'Viewport-Specific Isolation',
      fontSize: 19,
      fontWeight: 'bold',
      color: '#0f172a',
      marginBottom: 8,
    },
    overrides: {},
    revision: 1,
  },
  'feature-2-desc': {
    id: 'feature-2-desc',
    name: 'Feature 2 Description',
    type: 'text',
    parentId: 'feature-2',
    base: {
      text: 'Mobile-only edits apply strictly to mobile. Shared base edits cascade smoothly without overriding explicit viewport styles.',
      fontSize: 14,
      fontWeight: 'normal',
      color: '#475569',
      lineHeight: 1.6,
    },
    overrides: {},
    revision: 1,
  },
  'feature-3': {
    id: 'feature-3',
    name: 'Feature Card 3',
    type: 'card',
    parentId: 'features-grid',
    children: ['feature-3-badge', 'feature-3-title', 'feature-3-desc'],
    base: {
      backgroundColor: '#f8fafc',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: 14,
      paddingTop: 28,
      paddingBottom: 28,
      paddingLeft: 24,
      paddingRight: 24,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      textAlign: 'left',
    },
    overrides: {
      mobile: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 18,
        paddingRight: 18,
      },
    },
    revision: 1,
  },
  'feature-3-badge': {
    id: 'feature-3-badge',
    name: 'Feature 3 Badge',
    type: 'badge',
    parentId: 'feature-3',
    base: {
      text: 'GRANULAR RECOVERY',
      fontSize: 11,
      fontWeight: 'bold',
      color: '#15803d',
      backgroundColor: '#f0fdf4',
      borderRadius: 6,
      paddingTop: 4,
      paddingBottom: 4,
      paddingLeft: 10,
      paddingRight: 10,
      marginBottom: 16,
      letterSpacing: '0.04em',
    },
    overrides: {},
    revision: 1,
  },
  'feature-3-title': {
    id: 'feature-3-title',
    name: 'Feature 3 Title',
    type: 'heading',
    parentId: 'feature-3',
    base: {
      text: 'Per-Element Rollback',
      fontSize: 19,
      fontWeight: 'bold',
      color: '#0f172a',
      marginBottom: 8,
    },
    overrides: {},
    revision: 1,
  },
  'feature-3-desc': {
    id: 'feature-3-desc',
    name: 'Feature 3 Description',
    type: 'text',
    parentId: 'feature-3',
    base: {
      text: 'Restore any historical revision for one element and viewport without rolling back or disturbing unrelated work.',
      fontSize: 14,
      fontWeight: 'normal',
      color: '#475569',
      lineHeight: 1.6,
    },
    overrides: {},
    revision: 1,
  },

  // === TESTIMONIAL SECTION ===
  testimonial: {
    id: 'testimonial',
    name: 'Testimonial Section',
    type: 'section',
    children: ['testimonial-container'],
    base: {
      backgroundColor: '#fafafa',
      paddingTop: 72,
      paddingBottom: 72,
      paddingLeft: 24,
      paddingRight: 24,
      borderWidth: 1,
      borderColor: '#f1f5f9',
      width: '100%',
    },
    overrides: {
      mobile: {
        paddingTop: 44,
        paddingBottom: 44,
        paddingLeft: 16,
        paddingRight: 16,
      },
    },
    revision: 1,
  },
  'testimonial-container': {
    id: 'testimonial-container',
    name: 'Testimonial Container',
    type: 'container',
    parentId: 'testimonial',
    children: ['testimonial-card'],
    base: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      maxWidth: '820px',
      width: '100%',
    },
    overrides: {},
    revision: 1,
  },
  'testimonial-card': {
    id: 'testimonial-card',
    name: 'Testimonial Card',
    type: 'card',
    parentId: 'testimonial-container',
    children: ['testimonial-quote', 'testimonial-author', 'testimonial-role'],
    base: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: 16,
      paddingTop: 36,
      paddingBottom: 36,
      paddingLeft: 36,
      paddingRight: 36,
      textAlign: 'center',
      shadow: 'sm',
      width: '100%',
    },
    overrides: {
      mobile: {
        paddingTop: 24,
        paddingBottom: 24,
        paddingLeft: 20,
        paddingRight: 20,
      },
    },
    revision: 1,
  },
  'testimonial-quote': {
    id: 'testimonial-quote',
    name: 'Testimonial Quote',
    type: 'text',
    parentId: 'testimonial-card',
    base: {
      text: '“Scoped AI Template Editor completely removed the anxiety of breaking our production site during fast redesigns. The independent per-element restore gave our non-technical staff total confidence.”',
      fontSize: 18,
      fontWeight: 'medium',
      color: '#1e293b',
      lineHeight: 1.6,
      marginBottom: 20,
    },
    overrides: {
      mobile: {
        fontSize: 15,
        lineHeight: 1.5,
        marginBottom: 14,
      },
    },
    revision: 1,
  },
  'testimonial-author': {
    id: 'testimonial-author',
    name: 'Author Name',
    type: 'heading',
    parentId: 'testimonial-card',
    base: {
      text: 'Elena Rostova',
      fontSize: 16,
      fontWeight: 'bold',
      color: '#0f172a',
      marginBottom: 2,
    },
    overrides: {},
    revision: 1,
  },
  'testimonial-role': {
    id: 'testimonial-role',
    name: 'Author Role',
    type: 'text',
    parentId: 'testimonial-card',
    base: {
      text: 'VP of Digital Experience, Nexus Global',
      fontSize: 13,
      fontWeight: 'normal',
      color: '#64748b',
    },
    overrides: {},
    revision: 1,
  },

  // === FINAL CTA SECTION ===
  'final-cta': {
    id: 'final-cta',
    name: 'Final CTA Section',
    type: 'section',
    children: ['final-cta-container'],
    base: {
      backgroundColor: '#0f172a',
      paddingTop: 80,
      paddingBottom: 80,
      paddingLeft: 24,
      paddingRight: 24,
      width: '100%',
    },
    overrides: {
      mobile: {
        paddingTop: 48,
        paddingBottom: 48,
        paddingLeft: 16,
        paddingRight: 16,
      },
    },
    revision: 1,
  },
  'final-cta-container': {
    id: 'final-cta-container',
    name: 'Final CTA Container',
    type: 'container',
    parentId: 'final-cta',
    children: ['final-cta-title', 'final-cta-desc', 'final-cta-button'],
    base: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      maxWidth: '720px',
      width: '100%',
    },
    overrides: {},
    revision: 1,
  },
  'final-cta-title': {
    id: 'final-cta-title',
    name: 'Final CTA Title',
    type: 'heading',
    parentId: 'final-cta-container',
    base: {
      text: 'Ready to build with guaranteed visual safety?',
      fontSize: 34,
      fontWeight: 'bold',
      color: '#ffffff',
      lineHeight: 1.25,
      marginBottom: 16,
      letterSpacing: '-0.02em',
    },
    overrides: {
      mobile: {
        fontSize: 24,
      },
    },
    revision: 1,
  },
  'final-cta-desc': {
    id: 'final-cta-desc',
    name: 'Final CTA Description',
    type: 'text',
    parentId: 'final-cta-container',
    base: {
      text: 'Join over 2,400 product teams editing responsive websites with deterministic AI co-pilots and granular history recovery.',
      fontSize: 16,
      fontWeight: 'normal',
      color: '#94a3b8',
      lineHeight: 1.6,
      marginBottom: 28,
    },
    overrides: {
      mobile: {
        fontSize: 14,
        marginBottom: 20,
      },
    },
    revision: 1,
  },
  'final-cta-button': {
    id: 'final-cta-button',
    name: 'Final CTA Action Button',
    type: 'button',
    parentId: 'final-cta-container',
    base: {
      text: 'Claim Your Workspace Now →',
      fontSize: 15,
      fontWeight: 'bold',
      color: '#0f172a',
      backgroundColor: '#ffffff',
      borderRadius: 10,
      paddingTop: 13,
      paddingBottom: 13,
      paddingLeft: 28,
      paddingRight: 28,
      shadow: 'md',
    },
    overrides: {
      mobile: {
        width: '100%',
        textAlign: 'center',
      },
    },
    revision: 1,
  },

  // === FOOTER SECTION ===
  footer: {
    id: 'footer',
    name: 'Footer Section',
    type: 'section',
    children: ['footer-container'],
    base: {
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      paddingTop: 32,
      paddingBottom: 32,
      paddingLeft: 24,
      paddingRight: 24,
      width: '100%',
    },
    overrides: {
      mobile: {
        paddingTop: 24,
        paddingBottom: 24,
        paddingLeft: 16,
        paddingRight: 16,
      },
    },
    revision: 1,
  },
  'footer-container': {
    id: 'footer-container',
    name: 'Footer Container',
    type: 'container',
    parentId: 'footer',
    children: ['footer-brand', 'footer-copyright', 'footer-status'],
    base: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'between',
      maxWidth: '1200px',
      width: '100%',
    },
    overrides: {
      mobile: {
        flexDirection: 'column',
        gap: 12,
        textAlign: 'center',
      },
    },
    revision: 1,
  },
  'footer-brand': {
    id: 'footer-brand',
    name: 'Footer Brand Name',
    type: 'text',
    parentId: 'footer-container',
    base: {
      text: '✦ Aura Platform',
      fontSize: 14,
      fontWeight: 'bold',
      color: '#0f172a',
    },
    overrides: {},
    revision: 1,
  },
  'footer-copyright': {
    id: 'footer-copyright',
    name: 'Footer Copyright',
    type: 'text',
    parentId: 'footer-container',
    base: {
      text: '© 2026 Aura Technologies Inc. All rights reserved. Candidate hiring prototype.',
      fontSize: 12,
      fontWeight: 'normal',
      color: '#64748b',
    },
    overrides: {},
    revision: 1,
  },
  'footer-status': {
    id: 'footer-status',
    name: 'Footer Status Badge',
    type: 'badge',
    parentId: 'footer-container',
    base: {
      text: '● Schema v1.0 Validated',
      fontSize: 11,
      fontWeight: 'medium',
      color: '#15803d',
      backgroundColor: '#f0fdf4',
      borderRadius: 4,
      paddingTop: 2,
      paddingBottom: 2,
      paddingLeft: 8,
      paddingRight: 8,
    },
    overrides: {},
    revision: 1,
  },
};

export const INITIAL_TEMPLATE: TemplateModel = {
  templateId: 'template-aura-cloud-v1',
  name: 'Aura Cloud Platform (Responsive One-Page)',
  version: 1,
  elements,
  rootElementIds: ['header', 'hero', 'features', 'testimonial', 'final-cta', 'footer'],
  history: [
    {
      id: 'hist-init-0',
      timestamp: Date.now() - 3600000,
      source: 'canvas',
      summary: 'Initial template loaded from baseline canonical state',
      elementIds: ['hero-title'],
      viewport: 'all',
      baseRevision: 0,
      newRevision: 1,
      changes: {
        'hero-title': {
          elementName: 'Hero Title',
          before: {},
          after: { text: 'Build Safe Web Experiences with Scoped AI Precision' },
          targetViewport: 'all',
        },
      },
      snapshot: {
        'hero-title': elements['hero-title'],
      },
    },
  ],
};
